use crate::types::field::{
    BooleanConstraint, Condition, FieldCondition, FieldType, SchemaField, ValueConstraint,
};
use crate::types::node::{I18nValue, NodeDefine};
use std::collections::HashMap;

pub const NODE_TYPE: &str = "GPT";

#[derive(Default)]
pub struct GptNode;

impl GptNode {
    pub fn new() -> Self {
        Self {}
    }
}

impl NodeDefine for GptNode {
    fn action_type(&self) -> String {
        NODE_TYPE.to_string()
    }

    fn name(&self) -> I18nValue {
        I18nValue {
            zh: "ChatGPT".to_string(),
            en: "ChatGPT".to_string(),
        }
    }

    fn icon(&self) -> String {
        String::from(
            "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjRweCIgaGVpZ2h0PSIyNHB4IiB2aWV3Qm94PSItMSAtMSAyNiAyNiIgcm9sZT0iaW1nIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPjx0aXRsZT5PcGVuQUkgaWNvbjwvdGl0bGU+PHBhdGggZD0iTTIyLjI4MTkgOS44MjExYTUuOTg0NyA1Ljk4NDcgMCAwIDAtLjUxNTctNC45MTA4IDYuMDQ2MiA2LjA0NjIgMCAwIDAtNi41MDk4LTIuOUE2LjA2NTEgNi4wNjUxIDAgMCAwIDQuOTgwNyA0LjE4MThhNS45ODQ3IDUuOTg0NyAwIDAgMC0zLjk5NzcgMi45IDYuMDQ2MiA2LjA0NjIgMCAwIDAgLjc0MjcgNy4wOTY2IDUuOTggNS45OCAwIDAgMCAuNTExIDQuOTEwNyA2LjA1MSA2LjA1MSAwIDAgMCA2LjUxNDYgMi45MDAxQTUuOTg0NyA1Ljk4NDcgMCAwIDAgMTMuMjU5OSAyNGE2LjA1NTcgNi4wNTU3IDAgMCAwIDUuNzcxOC00LjIwNTggNS45ODk0IDUuOTg5NCAwIDAgMCAzLjk5NzctMi45MDAxIDYuMDU1NyA2LjA1NTcgMCAwIDAtLjc0NzUtNy4wNzI5em0tOS4wMjIgMTIuNjA4MWE0LjQ3NTUgNC40NzU1IDAgMCAxLTIuODc2NC0xLjA0MDhsLjE0MTktLjA4MDQgNC43NzgzLTIuNzU4MmEuNzk0OC43OTQ4IDAgMCAwIC4zOTI3LS42ODEzdi02LjczNjlsMi4wMiAxLjE2ODZhLjA3MS4wNzEgMCAwIDEgLjAzOC4wNTJ2NS41ODI2YTQuNTA0IDQuNTA0IDAgMCAxLTQuNDk0NSA0LjQ5NDR6bS05LjY2MDctNC4xMjU0YTQuNDcwOCA0LjQ3MDggMCAwIDEtLjUzNDYtMy4wMTM3bC4xNDIuMDg1MiA0Ljc4MyAyLjc1ODJhLjc3MTIuNzcxMiAwIDAgMCAuNzgwNiAwbDUuODQyOC0zLjM2ODV2Mi4zMzI0YS4wODA0LjA4MDQgMCAwIDEtLjAzMzIuMDYxNUw5Ljc0IDE5Ljk1MDJhNC40OTkyIDQuNDk5MiAwIDAgMS02LjE0MDgtMS42NDY0ek0yLjM0MDggNy44OTU2YTQuNDg1IDQuNDg1IDAgMCAxIDIuMzY1NS0xLjk3MjhWMTEuNmEuNzY2NC43NjY0IDAgMCAwIC4zODc5LjY3NjVsNS44MTQ0IDMuMzU0My0yLjAyMDEgMS4xNjg1YS4wNzU3LjA3NTcgMCAwIDEtLjA3MSAwbC00LjgzMDMtMi43ODY1QTQuNTA0IDQuNTA0IDAgMCAxIDIuMzQwOCA3Ljg3MnptMTYuNTk2MyAzLjg1NThMMTMuMTAzOCA4LjM2NCAxNS4xMTkyIDcuMmEuMDc1Ny4wNzU3IDAgMCAxIC4wNzEgMGw0LjgzMDMgMi43OTEzYTQuNDk0NCA0LjQ5NDQgMCAwIDEtLjY3NjUgOC4xMDQydi01LjY3NzJhLjc5Ljc5IDAgMCAwLS40MDctLjY2N3ptMi4wMTA3LTMuMDIzMWwtLjE0Mi0uMDg1Mi00Ljc3MzUtMi43ODE4YS43NzU5Ljc3NTkgMCAwIDAtLjc4NTQgMEw5LjQwOSA5LjIyOTdWNi44OTc0YS4wNjYyLjA2NjIgMCAwIDEgLjAyODQtLjA2MTVsNC44MzAzLTIuNzg2NmE0LjQ5OTIgNC40OTkyIDAgMCAxIDYuNjgwMiA0LjY2ek04LjMwNjUgMTIuODYzbC0yLjAyLTEuMTYzOGEuMDgwNC4wODA0IDAgMCAxLS4wMzgtLjA1NjdWNi4wNzQyYTQuNDk5MiA0LjQ5OTIgMCAwIDEgNy4zNzU3LTMuNDUzN2wtLjE0Mi4wODA1TDguNzA0IDUuNDU5YS43OTQ4Ljc5NDggMCAwIDAtLjM5MjcuNjgxM3ptMS4wOTc2LTIuMzY1NGwyLjYwMi0xLjQ5OTggMi42MDY5IDEuNDk5OHYyLjk5OTRsLTIuNTk3NCAxLjQ5OTctMi42MDY3LTEuNDk5N1oiLz48L3N2Zz4=",
        )
    }

    fn category(&self) -> Option<I18nValue> {
        Some(I18nValue {
            zh: "AI".to_string(),
            en: "AI".to_string(),
        })
    }

    fn description(&self) -> Option<I18nValue> {
        Some(I18nValue {
            zh: "调用 OpenAI 兼容的聊天模型，返回生成文本与用量。".to_string(),
            en: "Call an OpenAI-compatible chat model and return the generated text and usage."
                .to_string(),
        })
    }

    fn output_schema(&self, _input: HashMap<String, serde_json::Value>) -> Vec<SchemaField> {
        vec![
            SchemaField {
                name: "data".to_string(),
                field_type: FieldType::String,
                item_type: None,
                description: Some(I18nValue {
                    zh: "ChatGPT 节点生成的返回内容".to_string(),
                    en: "Return content generated by ChatGPT nodes".to_string(),
                }),
                enums: vec![],
                default: None,
                condition: None,
            },
            SchemaField {
                name: "prompt_tokens".to_string(),
                field_type: FieldType::Number,
                item_type: None,
                description: Some(I18nValue {
                    zh: "提示词消耗 token 数".to_string(),
                    en: "Prompt tokens used".to_string(),
                }),
                enums: vec![],
                default: None,
                condition: None,
            },
            SchemaField {
                name: "completion_tokens".to_string(),
                field_type: FieldType::Number,
                item_type: None,
                description: Some(I18nValue {
                    zh: "生成部分消耗 token 数".to_string(),
                    en: "Completion tokens used".to_string(),
                }),
                enums: vec![],
                default: None,
                condition: None,
            },
            SchemaField {
                name: "total_tokens".to_string(),
                field_type: FieldType::Number,
                item_type: None,
                description: Some(I18nValue {
                    zh: "总 token 消耗".to_string(),
                    en: "Total tokens used".to_string(),
                }),
                enums: vec![],
                default: None,
                condition: None,
            },
        ]
    }

    fn input_schema(&self) -> Vec<SchemaField> {
        vec![
            SchemaField {
                name: "api_key".to_string(),
                field_type: FieldType::Password,
                item_type: None,
                description: Some(I18nValue {
                    zh: "OpenAI API Key（为空则使用环境变量 OPENAI_API_KEY）".to_string(),
                    en: "OpenAI API key (falls back to OPENAI_API_KEY env var)".to_string(),
                }),
                enums: vec![],
                default: Some("".to_string()),
                condition: None,
            },
            SchemaField {
                name: "base_url".to_string(),
                field_type: FieldType::String,
                item_type: None,
                description: Some(I18nValue {
                    zh: "可选的 API Base URL，兼容自建或代理网关".to_string(),
                    en: "Optional API base URL for self-hosted or proxy gateways".to_string(),
                }),
                enums: vec![],
                default: Some("".to_string()),
                condition: None,
            },
            SchemaField {
                name: "model".to_string(),
                field_type: FieldType::String,
                item_type: None,
                description: Some(I18nValue {
                    zh: "模型名称，如 gpt-4o-mini".to_string(),
                    en: "Model name, e.g. gpt-4o-mini".to_string(),
                }),
                enums: vec![],
                default: Some("gpt-4o-mini".to_string()),
                condition: None,
            },
            SchemaField {
                name: "system_prompt_enabled".to_string(),
                field_type: FieldType::Boolean,
                item_type: None,
                description: Some(I18nValue {
                    zh: "是否设置系统提示词".to_string(),
                    en: "Should system prompts be enabled?".to_string(),
                }),
                enums: vec![],
                default: None,
                condition: None,
            },
            SchemaField {
                name: "system".to_string(),
                field_type: FieldType::String,
                item_type: None,
                description: Some(I18nValue {
                    zh: "系统提示词，可为空".to_string(),
                    en: "Optional system prompt".to_string(),
                }),
                enums: vec![],
                default: Some("".to_string()),
                condition: Some(Condition::Field(FieldCondition {
                    field: "system_prompt_enabled".to_string(),
                    constraint: ValueConstraint::Boolean(BooleanConstraint::from(true)),
                    required: false,
                })),
            },
            SchemaField {
                name: "prompt".to_string(),
                field_type: FieldType::String,
                item_type: None,
                description: Some(I18nValue {
                    zh: "用户提示词".to_string(),
                    en: "User prompt".to_string(),
                }),
                enums: vec![],
                default: None,
                condition: None,
            },
            // TODO: Support response json schema format
            // SchemaField {
            //     name: "response_format_enabled".to_string(),
            //     field_type: FieldType::Boolean,
            //     item_type: None,
            //     description: Some(I18nValue {
            //         zh: "是否自定义Json响应格式".to_string(),
            //         en: "Should the JSON response format be customized?".to_string(),
            //     }),
            //     enums: vec![],
            //     default: None,
            //     condition: None,
            // },
            // SchemaField {
            //     name: "response_json_schema".to_string(),
            //     field_type: FieldType::String,
            //     item_type: None,
            //     description: Some(I18nValue {
            //         zh: "设置JsonSchema，以Json的方式响应".to_string(),
            //         en: "Response JsonSchema Format".to_string(),
            //     }),
            //     enums: vec![],
            //     default: None,
            //     condition: Some(Condition::Field(FieldCondition {
            //         field: "response_format_enabled".to_string(),
            //         constraint: ValueConstraint::Boolean(BooleanConstraint::from(true)),
            //         required: false,
            //     })),
            // }
        ]
    }
}
